1. Create a class Employee and then do the following:

* Create a data member to count the number of Employees
* Create a constructor to initialize name, family, salary, department
* Create a function to average salary
* Create a Fulltime Employee class and it should inherit the properties of Employee class
* Create the instances of Fulltime Employee class and Employee class and call their member functions.


In [3]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Sai Ram", "Uppalapati", 100000, "Manager")
employee2 = Employee("Venkat", "Uppalapati", 90000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Madhavi", "Uppalapati", 75000, "Finance")
fulltime_employee2 = FulltimeEmployee("Nandhu", "Nandini", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)


Average Salary for Employees: 47500.0
Average Salary for Fulltime Employees: 33750.0


Using NumPy:

* create random vector of size 20 having only float in the range 1-20.
* Then reshape the array to 4 by 5
* Then replace the max in each row by 0 (axis=1)

Note: (you can NOT implement it via for loop)

In [ ]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 2.77180358 10.00637348 16.86616228  5.01560061 12.49094748  2.6903779
 16.1301691  13.3544305   4.28187936  3.09106015 19.20555751 11.89196345
 14.63234498 11.91538557 19.16973408  4.00768146  1.9696587   2.33131909
  4.6092697  11.9547249 ]


In [ ]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[ 2.77180358 10.00637348 16.86616228  5.01560061 12.49094748]
 [ 2.6903779  16.1301691  13.3544305   4.28187936  3.09106015]
 [19.20555751 11.89196345 14.63234498 11.91538557 19.16973408]
 [ 4.00768146  1.9696587   2.33131909  4.6092697  11.9547249 ]]


In [ ]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 2.77180358 10.00637348  0.          5.01560061 12.49094748]
 [ 2.6903779   0.         13.3544305   4.28187936  3.09106015]
 [ 0.         11.89196345 14.63234498 11.91538557 19.16973408]
 [ 4.00768146  1.9696587   2.33131909  4.6092697   0.        ]]
